### ISSUE TITLE
Generator-Liferay-Theme crashes on Node 8

### ISSUE THREAD

**Issue by sbaechler** [liferay/liferay-themes-sdk#43]
When I run the generator (8.0.0-beta.1) with Node 8 it crashes with the following message:

```
Error: Cannot find module 'internal/util/types'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at evalmachine.<anonymous>:31:26
    at Object.<anonymous> (/usr/local/lib/node_modules/generator-liferay-theme/node_modules/vinyl-fs/node_modules/graceful-fs/fs.js:32:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
```

Node 8 is the current LTS version. The generator is working with Node 6.

There are a few security notices as well:

```
WARN notice [SECURITY] mime has the following vulnerability: 1 moderate. Go here for more details: https://nodesecurity.io/advisories?search=mime&version=1.3.6 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
WARN notice [SECURITY] is-my-json-valid has the following vulnerability: 1 low. Go here for more details: https://nodesecurity.io/advisories?search=is-my-json-valid&version=2.16.0 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
WARN notice [SECURITY] lodash has the following vulnerability: 1 low. Go here for more details: https://nodesecurity.io/advisories?search=lodash&version=3.6.0 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
```

**Comment by jbalsas** [comment]
Hey @sbaechler, I've tested this both on Windows and OSX with node `v8.11.4`. Both seem to work just fine. 

This might be related to https://github.com/gulpjs/gulp/issues/2158. Could you try looking at that thread in case it rings a bell? The first suggestion is to run `npm rebuild`, or reinstalling everything.

**Comment by sbaechler** [comment]
I just tried it again with the newest version and it is working fine. Closing the issue.
