### ISSUE TITLE
Gulp deploy fails with newly created theme

### ISSUE THREAD

**Issue by mwilliams2014** [liferay/liferay-themes-sdk#68]
Error log:
C:\Users\liferay\Desktop\projects\demo-theme>gulp deploy
[13:56:06] Warning: You must install the correct dependencies, please run npm i --save-dev from your theme directory.
C:\Users\liferay\Desktop\projects\demo-theme\node_modules\liferay-theme-tasks\lib\doctor.js:143
                throw new Error('Missing ' + missingDeps + ' theme dependencies');
                ^

Error: Missing 1 theme dependencies
    at haltTask (C:\Users\liferay\Desktop\projects\demo-theme\node_modules\liferay-theme-tasks\lib\doctor.js:143:9)
    at doctor (C:\Users\liferay\Desktop\projects\demo-theme\node_modules\liferay-theme-tasks\lib\doctor.js:54:3)
    at register (C:\Users\liferay\Desktop\projects\demo-theme\node_modules\liferay-theme-tasks\index.js:57:2)
    at C:\Users\liferay\Desktop\projects\demo-theme\node_modules\liferay-plugin-node-tasks\index.js:37:4
    at arrayEach (C:\Users\liferay\Desktop\projects\demo-theme\node_modules\liferay-plugin-node-tasks\node_modules\lodash\lodash.js:516:11)
    at Function.forEach (C:\Users\liferay\Desktop\projects\demo-theme\node_modules\liferay-plugin-node-tasks\node_modules\lodash\lodash.js:9342:14)
    at Object.module.exports.registerTasks (C:\Users\liferay\Desktop\projects\demo-theme\node_modules\liferay-plugin-node-tasks\index.js:36:5)
    at Object.module.exports.registerTasks (C:\Users\liferay\Desktop\projects\demo-theme\node_modules\liferay-theme-tasks\index.js:18:21)
    at Object.<anonymous> (C:\Users\liferay\Desktop\projects\demo-theme\gulpfile.js:6:19)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Liftoff.handleArguments (C:\Users\liferay\AppData\Roaming\npm\node_modules\gulp\bin\gulp.js:116:3)
    at Liftoff.execute (C:\Users\liferay\AppData\Roaming\npm\node_modules\gulp\node_modules\liftoff\index.js:203:12)
    at module.exports (C:\Users\liferay\AppData\Roaming\npm\node_modules\gulp\node_modules\flagged-respawn\index.js:51:3)
    at Liftoff.<anonymous> (C:\Users\liferay\AppData\Roaming\npm\node_modules\gulp\node_modules\liftoff\index.js:195:5)
    at C:\Users\liferay\AppData\Roaming\npm\node_modules\gulp\node_modules\liftoff\index.js:165:9
    at C:\Users\liferay\AppData\Roaming\npm\node_modules\gulp\node_modules\v8flags\index.js:110:14
    at C:\Users\liferay\AppData\Roaming\npm\node_modules\gulp\node_modules\v8flags\index.js:38:12
    at C:\Users\liferay\AppData\Roaming\npm\node_modules\gulp\node_modules\v8flags\index.js:49:7
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:695:11)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3

**Comment by mwilliams2014** [comment]
Closing. This issue was resolved by manually changing the liferay-theme-deps 7.0 to 7.1 for the 7.1 theme. See https://github.com/liferay/liferay-themes-sdk/issues/71

**Comment by jbalsas** [comment]
Closing as duplicated. This will be fixed with the other, and as it is, it's not an issue.
