### ISSUE TITLE
Cannot read property 'help' of undefined when using gulp deploy on newly created theme

### ISSUE THREAD

**Issue by john-co** [liferay/liferay-themes-sdk#69]
~/my-liferay-theme$ gulp deploy
/home/john-co/my-liferay-theme/node_modules/gulp-help/index.js:81
    task = gulp.tasks[name];
                     ^

TypeError: Cannot read property 'help' of undefined
    at Gulp.gulp.task (/home/john-co/my-liferay-theme/node_modules/gulp-help/index.js:81:22)
    at module.exports (/home/john-co/my-liferay-theme/node_modules/gulp-help/index.js:97:8)
    at Object.module.exports.registerTasks (/home/john-co/my-liferay-theme/node_modules/liferay-plugin-node-tasks/index.js:17:9)
    at Object.module.exports.registerTasks (/home/john-co/my-liferay-theme/node_modules/liferay-theme-tasks/index.js:18:21)
    at Object.<anonymous> (/home/john-co/my-liferay-theme/gulpfile.js:6:19)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)

**Comment by jbalsas** [comment]
Hey @john-co, might bthis be the same as https://github.com/liferay/liferay-themes-sdk/issues/71 and https://github.com/liferay/liferay-themes-sdk/issues/68?

**Comment by mwilliams2014** [comment]
@jbalsas This is caused by something different. Should note I'm on Windows and he is on Linux.

**Comment by john-co** [comment]
Not reproducible on gulp v3.9.1. Looks like v4.0.0 isn't officially released yet and most likely gulp will fix it once v4.0.0 is released: https://www.npmjs.com/package/gulp. Closing issue.

**Comment by sebcramer** [comment]
Since gulp v4 has long since become stable (3.x is even unsupported now) and node >v12 doesn't support gulp-v3 anymore this issue should be reopened and fixed.

**Comment by jbalsas** [comment]
Hey @sebcramer, I've added [Upgrade to Gulp v4](https://github.com/liferay/liferay-js-themes-toolkit/issues/148) to the `7.3.x Support` milestone so we can work on it for the next version as it stands to reason that we'd start looking into it.

Please watch for developments over there for more information.

Thanks!
