### ISSUE TITLE
Deploy with gulp watch fails with NPE

### ISSUE THREAD

**Issue by chrberndt** [liferay/liferay-themes-sdk#94]
Re-Deploy with gulp watch crashes with the following stacktrace. telnet localhost 11311 is possible (portal-developer.properties are enabled via portal-ext.properties): 

2018-09-24 13:40:21.052 INFO  [Thread-52][BaseAutoDeployListener:43] Copying themes for /home/berndt/liferay/livingstone-fjord-theme/.web_bundle_build
2018-09-24 13:40:21.095 INFO  [Thread-52][ThemeAutoDeployer:81] Modifying themes for /home/berndt/liferay/livingstone-fjord-theme/.web_bundle_build
2018-09-24 13:40:21.122 INFO  [Thread-52][ThemeAutoDeployer:89] Themes for /home/berndt/liferay/livingstone-fjord-theme/.web_bundle_build modified successfully
2018-09-24 13:40:21.124 INFO  [Thread-52][BaseAutoDeployListener:50] Themes for /home/berndt/liferay/livingstone-fjord-theme/.web_bundle_build copied successfully
2018-09-24 13:40:21.142 ERROR [Thread-52][WabDirURLStreamHandlerService:128] Unable to open connection
java.lang.NullPointerException
	at aQute.bnd.osgi.Jar.getName(Jar.java:107)
	at aQute.bnd.osgi.Jar.<init>(Jar.java:99)
	at com.liferay.portal.osgi.web.wab.reference.support.internal.WabDirURLStreamHandlerService.openConnection(WabDirURLStreamHandlerService.java:116)
	at org.eclipse.osgi.internal.url.URLStreamHandlerProxy.openConnection(URLStreamHandlerProxy.java:114)
	at java.net.URL.openConnection(URL.java:979)
	at org.eclipse.osgi.storage.Storage.getContentConnection(Storage.java:441)
	at org.eclipse.osgi.storage.Storage.getContentConnection(Storage.java:417)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.installBundle(BundleContextImpl.java:145)
	at org.apache.felix.gogo.command.Basic.install(Basic.java:428)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.felix.gogo.runtime.Reflective.invoke(Reflective.java:137)
	at org.apache.felix.gogo.runtime.CommandProxy.execute(CommandProxy.java:82)
	at org.apache.felix.gogo.runtime.Closure.executeCmd(Closure.java:477)
	at org.apache.felix.gogo.runtime.Closure.executeStatement(Closure.java:403)
	at org.apache.felix.gogo.runtime.Pipe.run(Pipe.java:108)
	at org.apache.felix.gogo.runtime.Closure.execute(Closure.java:183)
	at org.apache.felix.gogo.runtime.Closure.execute(Closure.java:120)
	at org.apache.felix.gogo.runtime.CommandSessionImpl.execute(CommandSessionImpl.java:89)
	at org.apache.felix.gogo.shell.Console.run(Console.java:62)
	at org.apache.felix.gogo.shell.Shell.console(Shell.java:203)
	at org.apache.felix.gogo.shell.Shell.gosh(Shell.java:128)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.felix.gogo.runtime.Reflective.invoke(Reflective.java:137)
	at org.apache.felix.gogo.runtime.CommandProxy.execute(CommandProxy.java:82)
	at org.apache.felix.gogo.runtime.Closure.executeCmd(Closure.java:477)
	at org.apache.felix.gogo.runtime.Closure.executeStatement(Closure.java:403)
	at org.apache.felix.gogo.runtime.Pipe.run(Pipe.java:108)
	at org.apache.felix.gogo.runtime.Closure.execute(Closure.java:183)
	at org.apache.felix.gogo.runtime.Closure.execute(Closure.java:120)
	at org.apache.felix.gogo.runtime.CommandSessionImpl.execute(CommandSessionImpl.java:89)
	at org.eclipse.equinox.console.telnet.TelnetConnection.run(TelnetConnection.java:94)

**Comment by jbalsas** [comment]
Hey @chrberndt, can you add some additional information about your Liferay Portal version and OS environment where you're trying this?

**Comment by chrberndt** [comment]
@jbalsas sure: 

**Environment:**

Liferay 7.1.10 GA1 

```
berndt@x270:~$ uname -a; java -version
Linux x270 4.9.0-8-amd64 #1 SMP Debian 4.9.110-3+deb9u4 (2018-08-21) x86_64 GNU/Linux
openjdk version "1.8.0_181"
OpenJDK Runtime Environment (build 1.8.0_181-8u181-b13-1~deb9u1-b13)
OpenJDK 64-Bit Server VM (build 25.181-b13, mixed mode)
```
**How to reproduce:** 

1. Download and unpack 7.1.10 GA1  bundle
1. include-and-override=portal-developer.properties in portal-ext.properties
1. launch Liferay with LIFERAY_HOME/tomcat-9.0.6/bin/startup.sh
1. Deploy valid activation key
1. Create theme as documented at  https://dev.liferay.com/de/develop/tutorials/-/knowledge_base/7-1/creating-themes (yo liferay-theme - with default settings)
1. cd my-liferay-theme/
1. deploy with gulp watch
1. telnet localhost 11311
1. start my-liferay-theme bundle 
1. Login to Liferay
1. select "My Liferay Theme"
1. mkdir src/templates
1. cp build/templates/portal_normal.ftl src/templates

**Comment by chrberndt** [comment]
with the steps documented above, I now get the following output: 

2018-09-24 14:35:21.356 INFO  [Thread-42][BaseAutoDeployListener:43] Copying themes for /home/berndt/liferay/my-liferay-theme/.web_bundle_build
2018-09-24 14:35:21.390 INFO  [Thread-42][ThemeAutoDeployer:81] Modifying themes for /home/berndt/liferay/my-liferay-theme/.web_bundle_build
2018-09-24 14:35:21.413 INFO  [Thread-42][ThemeAutoDeployer:89] Themes for /home/berndt/liferay/my-liferay-theme/.web_bundle_build modified successfully
2018-09-24 14:35:21.415 INFO  [Thread-42][BaseAutoDeployListener:50] Themes for /home/berndt/liferay/my-liferay-theme/.web_bundle_build copied successfully
14:35:41.897 [elasticsearch[5OsS7Uz][masterService#updateTask][T#1]] INFO  org.elasticsearch.cluster.metadata.MetaDataMappingService - [liferay-20099/Vmx1lM9XSVafu4doPW6h6A] update_mapping [LiferayDocumentType]
14:35:41.949 [elasticsearch[5OsS7Uz][masterService#updateTask][T#1]] INFO  org.elasticsearch.cluster.metadata.MetaDataMappingService - [liferay-20099/Vmx1lM9XSVafu4doPW6h6A] update_mapping [LiferayDocumentType]
14:36:06.263 [elasticsearch[5OsS7Uz][scheduler][T#1]] INFO  org.elasticsearch.monitor.jvm.JvmGcMonitorService - [gc][340] overhead, spent [1.3s] collecting in the last [1.7s]
2018-09-24 14:39:00.437 INFO  [Thread-45][BundleStartStopLogger:35] STARTED my-liferay-theme_1.0.0 [960]
2018-09-24 14:39:00.635 INFO  [Thread-45][HotDeployImpl:226] Deploying my-liferay-theme from queue
2018-09-24 14:39:00.636 INFO  [Thread-45][PluginPackageUtil:1001] Reading plugin package for my-liferay-theme
24-Sep-2018 14:39:00.641 INFO [Thread-45] org.apache.catalina.core.ApplicationContext.log Initializing Spring root WebApplicationContext
2018-09-24 14:39:00.665 INFO  [Thread-45][ThemeHotDeployListener:93] Registering themes for my-liferay-theme
2018-09-24 14:39:01.187 INFO  [Thread-45][ThemeHotDeployListener:108] 1 theme for my-liferay-theme is available for use
2018-09-24 14:40:29.656 WARN  [http-nio-8080-exec-7][code_jsp:172] {code="404", msg="ProxyServlet: /o/my-liferay-theme/images/thumbnail.png", uri=/o/my-liferay-theme/images/thumbnail.png}
2018-09-24 14:40:32.582 WARN  [http-nio-8080-exec-5][code_jsp:172] {code="404", msg="ProxyServlet: /o/my-liferay-theme/images/thumbnail.png", uri=/o/my-liferay-theme/images/thumbnail.png}
2018-09-24 14:41:30.836 WARN  [http-nio-8080-exec-7][ThemeLocalServiceImpl:230] No theme found for specified theme id myliferay_WAR_myliferaytheme. Returning the default theme.

**Comment by chrberndt** [comment]
My initial report was probably tampered by a "gulp deploy" at some step

**Comment by chrberndt** [comment]
@jbalsas I did some further investigation and have updated the steps required to reproduce accordingly. In my first report I did not disable ftl caching - now it seems to work, despite the irritating WARNING in the log message. 
There is still a delay of some minutes until modifications of portal_normal.ftl are displayed - is there an additional cache setting we have to consider? https://dev.liferay.com/de/develop/tutorials/-/knowledge_base/7-1/using-developer-mode-with-themes mentions only Resource modification check

**Comment by chrberndt** [comment]
maybe related, maybe not: when list the installed bundles, I see multiple versions of classic-theme and admin-theme: 

...
  955|Active     |   10|admin-theme (2.0.6)
  956|Active     |   10|classic-theme (2.0.0)
  957|Active     |   10|lcs-portlet (7.0.10.72)
  958|Active     |   10|admin-theme (2.0.0)
  959|Active     |   10|classic-theme (2.0.7)
  960|Active     |    1|my-liferay-theme (1.0.0)

**Comment by chrberndt** [comment]
Update after long delay works only for modifications of portal_normal.ftl - modifications of src/css/_custom.css are reported but not reflected on the server side: 

[18:00:56] Starting 'deploy:file'...
[18:00:56] gulp-debug: src/css/_custom.scss
[18:00:56] gulp-debug: 1 item
[18:00:56] Finished 'deploy:file' after 5.4 ms
[Browsersync] Reloading Browsers...

**Comment by chrberndt** [comment]
I think this ticket is no obsolete, since we have a better report for https://github.com/liferay/liferay-themes-sdk/issues/102

**Comment by chrberndt** [comment]
I wouldn't object, though I have the feeling, that the NPEs are caused when you use `gulp watch`and `gulp deploy` side by side. I closed it, since I couldn't provide a path of how to reproduce the issue.

**Comment by deadcyclo** [comment]
I vote for reopening. I'm having the exact same problem. And I've tried doing it on a complete virgin DXP 7.1 without gulp deploy ever being run, and the exact same issue occurs.

**Comment by deadcyclo** [comment]
appologies. The NPE was due to https://issues.liferay.com/browse/LPS-83547 fixed in the latest fix pack. Still not getting reloads though. I'll move over to #102
